title: International Press journal CNTP author support
description: TeX related material for the manuscript preparation for the
             International Press journal Communications in Number Theory and Physics (CNTP)
show_downloads: true
theme: jekyll-theme-tactile
